services:
  - type: web
    name: lykoonadds
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "bash start.sh"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_FORCE_HTTPS
        value: "True"
      - key: DJANGO_EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: DJANGO_EMAIL_HOST
        value: "smtp.gmail.com"
      - key: DJANGO_EMAIL_PORT
        value: "587"
      - key: DJANGO_EMAIL_USER
        sync: false
      - key: DJANGO_EMAIL_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: GOOGLE_ANALYTICS_ID
        sync: false
